1
[I 120712 12:17:59 web:1393] 200 GET / (127.0.0.1) 979.69ms
[I 120712 12:18:15 web:1393] 200 GET /about (127.0.0.1) 45.75ms
[I 120712 12:18:24 web:1393] 200 GET /photos/latest (127.0.0.1) 32.41ms
[I 120712 12:18:28 web:1393] 200 GET /photos/hot (127.0.0.1) 34.36ms
[I 120712 13:44:16 web:1393] 200 GET / (127.0.0.1) 139.93ms
[I 120712 14:48:24 web:1393] 200 GET /register?invite_key=925ab9089978832b (127.0.0.1) 175.94ms
[I 120712 14:48:59 web:1393] 200 POST /register?invite_key=925ab9089978832b (127.0.0.1) 216.94ms
[I 120712 14:48:59 web:1393] 200 GET / (127.0.0.1) 134.93ms
[I 120712 14:49:10 web:1393] 200 GET /login (127.0.0.1) 22.59ms
[I 120712 14:49:26 web:1393] 302 POST /login (127.0.0.1) 7.72ms
[I 120712 14:49:26 web:1393] 200 GET / (127.0.0.1) 142.29ms
[I 120712 14:49:33 web:1393] 304 GET /photos/hot (127.0.0.1) 28.65ms
[I 120712 14:49:35 web:1393] 304 GET /photos/latest (127.0.0.1) 28.63ms
[I 120712 14:49:37 web:1393] 304 GET /photos/hot (127.0.0.1) 32.95ms
[I 120712 14:49:37 web:1393] 304 GET /photos/latest (127.0.0.1) 32.87ms
[I 120712 15:30:52 web:1393] 200 GET /about (127.0.0.1) 19.29ms
[I 120714 10:45:43 web:1393] 200 GET / (127.0.0.1) 332.26ms
[I 120716 06:45:56 web:1393] 200 GET / (127.0.0.1) 899.86ms
[I 120716 06:45:59 web:1393] 200 GET /about (127.0.0.1) 19.06ms
[I 120716 06:46:44 web:1393] 200 GET / (127.0.0.1) 104.07ms
[I 120716 06:47:25 web:1393] 200 GET /about (127.0.0.1) 22.00ms
[I 120716 06:54:49 web:1393] 200 GET /about (127.0.0.1) 14.29ms
[I 120716 06:54:54 web:1393] 200 GET / (127.0.0.1) 102.69ms
[I 120716 07:00:43 web:1393] 200 GET /about (127.0.0.1) 13.38ms
[I 120716 07:03:13 web:1393] 200 GET / (127.0.0.1) 103.05ms
[I 120716 07:09:43 web:1393] 200 GET / (127.0.0.1) 115.02ms
[I 120716 07:09:47 web:1393] 200 GET /about (127.0.0.1) 15.81ms
[I 120717 11:01:15 web:1393] 200 GET / (127.0.0.1) 664.15ms
[I 120717 11:01:23 web:1393] 200 GET /login (127.0.0.1) 45.93ms
[I 120717 11:11:18 web:1393] 200 GET / (127.0.0.1) 109.14ms
[I 120717 11:13:10 autoreload:133] /home/dk/work/python/safood/src/sites/www/handlers/base.py modified; restarting server
[I 120717 11:15:15 web:1393] 200 GET / (127.0.0.1) 225.16ms
[I 120717 11:15:19 web:1393] 200 GET /about (127.0.0.1) 14.20ms
[I 120717 11:16:49 web:1393] 302 POST /login (127.0.0.1) 30.22ms
[I 120717 11:16:49 web:1393] 200 GET /login?error=%E8%AF%A5%E7%94%A8%E6%88%B7%E4%B8%8D%E5%AD%98%E5%9C%A8 (127.0.0.1) 14.79ms
[I 120717 11:16:56 web:1393] 302 POST /login?error=%C3%A8%C2%AF%C2%A5%C3%A7%C2%94%C2%A8%C3%A6%C2%88%C2%B7%C3%A4%C2%B8%C2%8D%C3%A5%C2%AD%C2%98%C3%A5%C2%9C%C2%A8 (127.0.0.1) 8.10ms
[I 120717 11:16:56 web:1393] 200 GET / (127.0.0.1) 106.66ms
[I 120717 11:17:25 autoreload:133] /home/dk/work/python/safood/src/sites/www/handlers/base.py modified; restarting server
[I 120717 11:17:37 autoreload:133] /home/dk/work/python/safood/src/sites/www/handlers/base.py modified; restarting server
[I 120717 11:17:46 autoreload:133] /home/dk/work/python/safood/src/sites/www/handlers/base.py modified; restarting server
[I 120717 11:20:08 web:1393] 200 GET /photo/upload (127.0.0.1) 232.68ms
[I 120717 11:21:44 web:1393] 302 POST /login (127.0.0.1) 19.75ms
[I 120717 11:21:44 web:1393] 200 GET / (127.0.0.1) 129.09ms
[E 120717 11:22:02 web:1031] Uncaught exception GET /photo (127.0.0.1)
    HTTPRequest(protocol='http', host='192.168.0.189', method='GET', uri='/photo', version='HTTP/1.0', remote_ip='127.0.0.1', body='', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip,deflate,sdch', 'X-Forwarded-For': '192.168.0.109', 'X-Scheme': 'http', 'Connection': 'close', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.46 Safari/535.11', 'Accept-Charset': 'GBK,utf-8;q=0.7,*;q=0.3', 'Host': '192.168.0.189', 'Cookie': 'Hm_lvt_005883a40039a7a54e1234b1ec574be5=1342060704129; __utma=148685175.2108842575.1342494076.1342494076.1342494076.1; __utmb=148685175.11.10.1342494076; __utmc=148685175; __utmz=148685175.1342494076.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)', 'X-Real-Ip': '192.168.0.109'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 988, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
    TypeError: get() takes exactly 2 arguments (1 given)
[E 120717 11:22:02 web:1393] 500 GET /photo (127.0.0.1) 136.74ms
[W 120717 11:22:02 web:1393] 404 GET /favicon.ico (127.0.0.1) 1.07ms
[I 120717 11:22:15 web:1393] 200 GET /photo/upload (127.0.0.1) 78.46ms
[W 120717 11:28:51 web:1393] 403 POST /photo (127.0.0.1) 2.70ms
[I 120717 11:38:20 web:1393] 200 GET /photo/upload (127.0.0.1) 60.27ms
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 10, in <module>
    from base import BaseHandler, BasePhotosHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 7, in <module>
    from macros.macro import ADDITIVES_PER_PAGE, USERS_PER_PAGE
ImportError: cannot import name ADDITIVES_PER_PAGE
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 10, in <module>
    from base import BaseHandler, BasePhotosHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 7, in <module>
    from macros.macro import ADDITIVES_PER_PAGE, USERS_PER_PAGE
ImportError: cannot import name ADDITIVES_PER_PAGE
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 10, in <module>
    from base import BaseHandler, BasePhotosHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 7, in <module>
    from macros.macro import ADDITIVES_PER_PAGE, USERS_PER_PAGE
ImportError: cannot import name ADDITIVES_PER_PAGE
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 10, in <module>
    from base import BaseHandler, BasePhotosHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 7, in <module>
    from macros.macro import ADDITIVES_PER_PAGE, USERS_PER_PAGE
ImportError: cannot import name ADDITIVES_PER_PAGE
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 10, in <module>
    from base import BaseHandler, BasePhotosHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 7, in <module>
    from macros.macro import ADDITIVES_PER_PAGE, USERS_PER_PAGE
ImportError: cannot import name ADDITIVES_PER_PAGE
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 9, in <module>
    from base import BaseHandler, BaseAdditivesHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 6, in <module>
    import models
  File "/home/dk/work/python/safood/src/common/models/__init__.py", line 7, in <module>
    from .activity import Activity
  File "/home/dk/work/python/safood/src/common/models/activity.py", line 10, in <module>
    photo_create = signal(EVENTS['PHOTO_CREATE'])
KeyError: 'PHOTO_CREATE'
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 9, in <module>
    from base import BaseHandler, BaseAdditivesHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 6, in <module>
    import models
  File "/home/dk/work/python/safood/src/common/models/__init__.py", line 7, in <module>
    from .activity import Activity
  File "/home/dk/work/python/safood/src/common/models/activity.py", line 10, in <module>
    photo_create = signal(EVENTS['PHOTO_CREATE'])
KeyError: 'PHOTO_CREATE'
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 9, in <module>
    from base import BaseHandler, BaseAdditivesHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 6, in <module>
    import models
  File "/home/dk/work/python/safood/src/common/models/__init__.py", line 7, in <module>
    from .activity import Activity
  File "/home/dk/work/python/safood/src/common/models/activity.py", line 10, in <module>
    photo_create = signal(EVENTS['PHOTO_CREATE'])
KeyError: 'PHOTO_CREATE'
Traceback (most recent call last):
  File "src/sites/www/app.py", line 12, in <module>
    import routes
  File "/home/dk/work/python/safood/src/sites/www/routes.py", line 1, in <module>
    from handlers import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/__init__.py", line 2, in <module>
    from handlers.home import *
  File "/home/dk/work/python/safood/src/sites/www/handlers/home.py", line 9, in <module>
    from base import BaseHandler, BaseAdditivesHandler
  File "/home/dk/work/python/safood/src/sites/www/handlers/base.py", line 6, in <module>
    import models
  File "/home/dk/work/python/safood/src/common/models/__init__.py", line 7, in <module>
    from .activity import Activity
  File "/home/dk/work/python/safood/src/common/models/activity.py", line 10, in <module>
    photo_create = signal(EVENTS['PHOTO_CREATE'])
KeyError: 'PHOTO_CREATE'
